version: "3.7"
services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./api:/var/www

  db:
    volumes:
      - ./DB:/docker-entrypoint-initdb.d/:rw
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest_api
      MYSQL_USER: kaszanka
      MYSQL_PASSWORD: root
    ports:
      - 6033:3306

